swagger: "2.0"
info:
  version: "0.2.0"
  title: FreeCodeCamp - Chart the Stock Market (Hey)
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - https
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /stocks:
    # binds a127 app logic to a route
    x-swagger-router-controller: stocks
    get:
      description: Returns list of stocks
      # used as the method name of the controller
      operationId: getStocks
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/StocksResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /stocks/add/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: stocks
    post:
      parameters:
        - in: path
          name: id   # Note the name is the same as in the path
          required: true
          type: string
          description: The underlying ID.
      description: Add a stock to the list
      # used as the method name of the controller
      operationId: addStock
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/StockAdditionResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  StocksResponse:
    type: array
    items:
      $ref: "#/definitions/Stocks"
  StockAdditionResponse:
    required:
      - added
    properties:
      added:
        type: boolean
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Stocks:
    required:
      - underlyingId
    properties:
      underlyingId:
        type: string
        description: The ID for the stock instrument.